### ISSUE TITLE
Missing category argument in translation causing exception

### ISSUE THREAD

**Issue by deling** [barrelstrength/craft-sprout-lists#12]
https://github.com/barrelstrength/craft-sprout-lists/blob/c7f8d27762a90423f7430da1d842e5d9f56d6189/src/elements/Subscribers.php#L74

[Craft 3 requires t() to include a category argument.](https://docs.craftcms.com/v3/updating-plugins.html#translations) This is throwing a Yii exception when Sprout Lists is used alongside the Audit plugin, which is trying to get the display name for the Subscribers element type.

I checked the rest of the project and $category doesn't seem to be missing anywhere else.

PR with the fix: #13

**Comment by BenParizek** [comment]
Thanks @deling. This has been fixed and released in Sprout Lists v1.0.0-beta.10
