### ISSUE TITLE
Unable to create a list dynamically

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-lists#15]
When trying to create a list dynamically from the front-end, Sprout Lists throws an error.

In the following subscribe code, the list doesn't exist yet:

```
<form method="post" accept-charset="utf-8">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="sprout-lists/lists/subscribe">
    <input type="hidden" name="listHandle" value="listHandle{{ entry.slug }}">
    <input type="hidden" name="elementId" value="{{ entry.id }}">
    <input type="hidden" name="userId" value="{{ currentUser.id }}">
    <input type="submit" value="Add to List">
</form>
```

And throws the error: _No list could be found with the handle_

It seems this is happening in the `actionSubscribe` method on line 163:

```
$listType = SproutLists::$app->lists->getListTypeByHandle($subscription->listHandle);
```

When that fails, the SubscriberListType Class never has a chance to call the `getOrCreateList` method.

**Comment by BenParizek** [comment]
We may want to add a setting that a user can enable called 'Create Lists Dynamically'

This setting would help us determine if we should throw an error if a list handle is incorrect or return null and default to a `SubscriberListType` if a handle is new.

**Comment by pdaleramirez** [comment]
@BenParizek I have fixed the bug and added create auto list setting. I also added new sprout lists variable getErrors that displays error when subscribe fails
