### ISSUE TITLE
Improve PHP 7.2 Support

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-lists#28]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gyq3)

**Comment by pdaleramirez** [comment]
Added is_array before the count method on if condition to fix the issue committed here https://github.com/barrelstrength/craft-sprout-lists/commit/60f7a9d8837373cd24457d413f997d0bce55326a

**Comment by pdaleramirez** [comment]
Joel just need to update sprout-email and sprout-list latest craft2 version
sprout-email: v3.1.3
sprout-lists: v0.8.1

**Comment by pdaleramirez** [comment]
Tracked the Stacktrace.htm and I found out that he using a lower version of craft. I checked on Craft version 2.6.2922 version and open that file /craft/app/framework/db/ar/CActiveFinder.php it is the same code on the Stacktrace.html. He needs to update hi /app/ folder to 2.7.4 to fix the issue.
