### ISSUE TITLE
Error when subscriber doesn't exist

### ISSUE THREAD

**Issue by Moskydesign** [barrelstrength/craft-sprout-lists#29]
### Description

When trying to subscribe with a user id that isn't in the list yet a "Trying to get property 'id' of non-object" is thrown in "/listtypes/SubscriberListType.php" on line 517

```
        /** @var SubscribersRecord $subscriberRecord */
        $subscriberRecord = SubscribersRecord::find()->where($attributes)->one();

        /** @var Subscriber $subscriber */
        $subscriber = Craft::$app->getElements()->getElementById($subscriberRecord->id);
```
 
The problem here is that even when $subscriberRecord is empty it tries do get an id.
Changing this to:
```
       /** @var Subscriber $subscriber */
        if ($subscriberRecord) {
            $subscriber = Craft::$app->getElements()->getElementById($subscriberRecord->id);
        }
```

Fixes the issue.

**Comment by BenParizek** [comment]
@Moskydesign This should be resolved in the latest release (v2.0.0-rc.2)
