### ISSUE TITLE
How does it work? - Unable to set User Element ID as List ID

### ISSUE THREAD

**Issue by Moskydesign** [barrelstrength/craft-sprout-lists#30]
I'm a bit puzzled to how this plugin is supposed to be used.
Seeing the example code and description I was under the impression you could create a kind of favorites list with it.

The setup I have now is that each entry has a button to like the entry. I created a list in the backend "favorites" and do a post, as in the example, with the list handle, entry id and the user id.
So far so good.

But when I tried to retrieve the entries "liked" by the user I couldn't make sense of it. Since there was no function to get them, I looked in the database an saw that the element (entry) id was saved in the same record as the list and every time I liked a new entry it got overridden with that id.

So it doesn't work the way I thought it would work.
I now think the idea is that you can create a list like "newsletter" and people can subscribe to it, but then what is the "elementId" column for?
Is what I'm trying to achieve possible with this plugin?

**Comment by BenParizek** [comment]
Hi @Moskydesign. In looking into this, I believe you've run into a bug. 

For a Favorites list, you'd want to treat the User Element ID as the List ID, and the List would be any Element IDs you associate with that User List ID. But that doesn't appear to be working at the moment so I'll get that in our queue and update this thread once we get a fix out.

**Comment by BenParizek** [comment]
@Moskydesign The fix for this has taken us in the direction of an update to the underlying plugin structure around Favorites lists. We hope to have a solution out soon.

**Comment by BenParizek** [comment]
@Moskydesign We've recently released an updated version of Sprout Lists. Several things have been refactored and the docs have been updated. This is a major release, so be sure to read the upgrade instructions if you are using this on an existing site
https://sprout.barrelstrengthdesign.com/docs/lists/

To speak more specifically to your Favorites use case, Sprout Lists may not be the best fit for that use case right now. While it can track that data, Sprout Lists default List Type is more like a Mailing List (A relationship between some entity and a Susbcriber, who you can send an email too).  

The favorites use case is kind of the opposite of that, where you have a User, and they have a list of Items. Sprout Lists can potentially handle this, and we may add more specific updates to support this use case in the future, but the current List implementation is more focused on Mailing Lists and we've tried to make the updates of the latest release emphasize that more clearly.
