### ISSUE TITLE
Add documentation for redirects

### ISSUE THREAD

**Issue by danielvivacqua** [barrelstrength/craft-sprout-lists#31]
### Description

I am using the plugin and am trying to make it so that when a user hits the `<input type="submit" ...>` button, they are redirected to a "thank you" page. I referred to the Sprout Forms documentation but the methods described there did not apply to the Sprout List when I tried to use them. Please advise.

### Steps to reproduce

1. Create a typical Sprout list, similar to the examples in the current documentation
2. Before or after the line that starts `<input type="submit"`, add (for Craft 3) `{{ redirectInput('thanks') }}` after having created a `thanks.twig` template.
3. Note how it does not redirect.

### Additional info

- Craft version: Craft Pro 3.1.23
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:
  - CacheClear - 1.0.1
  - Contact Form - 2.2.4
  - Contact Form Honeypot - 1.0.2
  - Position Fieldtype - 1.0.14
  - Redactor - 2.3.2
  - Sprout Lists - 2.0.0-rc.2
  - Video Embedder - 1.1.1

**Comment by pdaleramirez** [comment]
I tested with a craft site that has only sprout-lists plugin installed and i could not recreate this issue.
Adding {{ redirectInput('thanks') }} redirected just fine

**Comment by BenParizek** [comment]
@danielvivacqua We haven't been able to recreate this. If the issue continues for you, can you post a full code example so we can make sure we're not overlooking anything obvious in our tests?

**Comment by BenParizek** [comment]
@danielvivacqua As we haven't heard back from you on this one, I'm closing it out for now. Feel free to reopen if the issue continues.

**Comment by danielvivacqua** [comment]
@BenParizek sorry about not responding, I realized what was wrong with my code (last week) and fixed it. Thank you.

**Comment by BenParizek** [comment]
@danielvivacqua No problem. Glad you got it sorted!
